image: node:8

stages:
- test
- build
- review

test package:
    stage: test
    script:
        - npm install
        - npm run lint
        - npm run test
    tags:
    - cm-official-docker-executor

build package:
  image: f5devcentral/containthedocs:rpmbuild
  stage: build
  script:
  - echo 'CI BUILD'
  # install packages first
  - npm install --production
  # run build_rpm script
  - bash ./scripts/build_rpm.sh
  tags:
  - cm-official-docker-executor
  artifacts:
    name: f5-telemetry-$CI_BUILD_REF
    paths:
    - dist
    expire_in: 1 month

build docs:
    image: ${CONTAINTHEDOCS_IMAGE}
    script:
        - make html
        - vale --glob='*.{md,rst}' .
      #  - make linkcheck
    tags:
        - docker-executor
    stage: build
    artifacts:
        name: docs
        paths:
            - docs/_build/html
        expire_in: 1 month

docs to pages:
    image: ${CONTAINTHEDOCS_IMAGE}
    stage: review
    environment:
        name: staging
        url: https://${CI_PROJECT_NAMESPACE}.${PAGES_DOMAIN}/${CI_PROJECT_NAME}
    tags:
        - cm-official-docker-executor
    dependencies:
        - build docs
    script:
        - mkdir -p ./public
        - cp -R docs/_build/html/* ./public
    artifacts:
        paths:
            - public
    only:
        - docs-vanessa@cloudsolutions/f5-telemetry

# Publish docs to clouddocs.f5networks.net
docs to staging:
  image: ${CONTAINTHEDOCS_IMAGE}
  stage: review
  environment: 
    name: staging
    url: https://clouddocs.f5networks.net/products/extensions/f5-telemetry-streaming/latest
  tags:
    - cm-official-docker-executor
  only:
    - develop@cloudsolutions/f5-telemetry
  dependencies:
    - build docs
  script:
    - aws s3 sync docs/_build/html s3://clouddocs.f5networks.net/products/extensions/f5-telemetry-streaming/latest
    # - aws s3 cp versions.json s3://clouddocs.f5networks.net/products/extensions/f5-telemetry-streaming/versions.json
    # create invalidation to clear cloudfront cache
    - aws cloudfront create-invalidation --distribution-id $AWS_DIST --paths /products/extensions/f5-telemetry-streaming/latest

# Publish docs to clouddocs.f5.com
docs to production:
  image: ${CONTAINTHEDOCS_IMAGE}
  stage: review
  environment:
    name: production
    url: https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest
  only:
  # fill in desired release branch name to add deployment from a branch: currently *master*
  - master@cloudsolutions/f5-telemetry
  tags:
  - cm-official-docker-executor
  dependencies:
  - build docs
  script:
  # Uncomment and set to create desired version format
    - aws s3 sync docs/_build/html s3://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest
    # - aws s3 cp versions.json s3://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/versions.json
    # create invalidation to clear cloudfront cache
    - aws cloudfront create-invalidation --distribution-id $AWS_DIST --paths /products/extensions/f5-telemetry-streaming/latest
