image: node:6.14.4

stages:
- test
- build

test package:
    image: f5devcentral/containthedocs:rpmbuild
    stage: test
    script:
        - echo 'Running Tests'
        - npm install
        - npm run lint
    tags:
    - cm-official-docker-executor

rpm build:
  image: f5devcentral/containthedocs:rpmbuild
  stage: build
  script:
  - echo 'CI BUILD'
  # install packages first
  - npm install --production
  # run build_rpm script
  - bash ./scripts/build_rpm.sh
  tags:
  - cm-official-docker-executor
  artifacts:
    name: f5-telemetry-$CI_BUILD_REF
    paths:
    - dist
    expire_in: 1 month