image: node:6.14.4

stages:
    - test
    - build
    - review
test package:
    image: f5devcentral/containthedocs:rpmbuild
    stage: test
    script:
        - echo 'Running Tests'
        - npm install
        - npm run lint
    tags:
        - cm-official-docker-executor
rpm build:
    image: f5devcentral/containthedocs:rpmbuild
    stage: build
    script:
        - echo 'CI BUILD'
        - npm install --production
        - RELEASE=$(($(ls -v dist/*.rpm|tail -1|sed -rn 's/.*-([0-9]+).noarch.rpm/\1/p') + 1))
        - MAINDIR=$(pwd)
        - rpmbuild -bb --define "main $(pwd)" --define '_topdir %{main}/rpmbuild' --define "_name f5-telemetry" --define "_release ${RELEASE}" f5-telemetry.spec
        - cd rpmbuild/RPMS/noarch
        - FN=$(ls -t *.rpm 2>/dev/null | head -1)
        - cp ${FN} ${MAINDIR}/dist
        - sha256sum "${FN}" > "${MAINDIR}/dist/${FN}.sha256"
        - cd ${MAINDIR}
        - echo "RPM FILE dist/${FN}"
    tags:
        - cm-official-docker-executor
    artifacts:
        name: f5-telemetry-$CI_BUILD_REF
        paths:
            - dist
        expire_in: 1 month
build docs:
    image: quay.pdsea.f5net.com/doc-ops/containthedocs:710e05a8ed
    script:
        - make html
    tags:
        - docker-executor
    stage: build
    artifacts:
        paths:
            - docs/_build/html
test grammar:
    image: quay.pdsea.f5net.com/doc-ops/containthedocs:710e05a8ed
    stage: review
    tags:
        - docker-executor
    script:
        - vale --glob='*.{md,rst}' .
test links:
    image: quay.pdsea.f5net.com/doc-ops/containthedocs:710e05a8ed
    stage: review
    tags:
        - docker-executor
    script:
        - make linkcheck
pages:
    image: quay.pdsea.f5net.com/doc-ops/containthedocs:710e05a8ed
    stage: review
    environment:
        name: review
        url: https://${CI_PROJECT_NAMESPACE}.pages.gitswarm.f5net.com/${CI_PROJECT_NAME}
    tags:
        - cm-official-docker-executor
    dependencies:
        - build docs
    script:
        - mkdir -p ./public
        - cp -R docs/_build/html/* ./public
    artifacts:
        paths:
            - public
    only:
        - branches

Publish docs to staging:
  image: quay.pdsea.f5net.com/doc-ops/containthedocs:710e05a8ed
  stage: review
  environment: 
    name: staging
    url: https://clouddocs.f5networks.net/products/extensions/telemetry-services/latest
  tags:
    - cm-official-docker-executor
  only:
    - docs-staging@cloudsolutions/f5-telemetry-services
  dependencies:
    - build docs
  script:
    - aws s3 sync docs/_build/html s3://clouddocs.f5networks.net/products/extensions/telemetry-services/latest
    # - aws s3 cp versions.json s3://clouddocs.f5networks.net/products/extensions/telemetry-services/versions.json
    # create invalidation to clear cloudfront cache
    - aws cloudfront create-invalidation --distribution-id $AWS_DIST --paths /products/extensions/telemetry-services/latest

# Publish docs to clouddocs.f5.com
docs to production:
  image: quay.pdsea.f5net.com/doc-ops/containthedocs:710e05a8ed
  stage: review
  environment:
    name: production
    url: https://clouddocs.f5.com/products/extensions/telemetry-services/latest
  only:
  # Currently will only deploy to clouddocs.f5.com on commits to doc-publish
  # fill in desired release branch name and uncomment to add deployment from a branch
  - docs-publish@cloudsolutions/f5-telemetry-services
  tags:
  - cm-official-docker-executor
  dependencies:
  - build docs
  script:
  # Uncomment and set to create desired version format
    - aws s3 sync docs/_build/html s3://clouddocs.f5.com/products/extensions/telemetry-services/latest
    # - aws s3 cp versions.json s3://clouddocs.f5.com/products/extensions/telemetry-services/versions.json
    # create invalidation to clear cloudfront cache
    - aws cloudfront create-invalidation --distribution-id $AWS_DIST --paths /products/extensions/telemetry-services/latest
